#ifndef MAIN_CFG_H
#define MAIN_CFG_H

#define LV_TICK_PERIOD_MS 1
#define GUI_TO_CONTROLLER_TASK_DELAY_MS 100
#define GUI_TASK_DELAY_MS 10
#define UPDATE_GUI_VAR_TASK_DELAY_MS 2000

#endif /* MAIN_CFG_H */